"""Stable Workflow Validation codes.

These codes are the public contract between the Backend Validation Engine, the
API and the Frontend. Frontend must never parse `message` strings; it keys off
`code`. Add new codes only when a rule genuinely needs a distinct signal.
"""

from enum import StrEnum


class ValidationCode(StrEnum):
    # --- Graph / identity ---
    GRAPH_EMPTY = "GRAPH_EMPTY"
    DUPLICATE_NODE_ID = "DUPLICATE_NODE_ID"
    DUPLICATE_EDGE_ID = "DUPLICATE_EDGE_ID"
    INVALID_EDGE_SOURCE = "INVALID_EDGE_SOURCE"
    INVALID_EDGE_TARGET = "INVALID_EDGE_TARGET"
    SELF_CONNECTION = "SELF_CONNECTION"
    DUPLICATE_CONNECTION = "DUPLICATE_CONNECTION"

    # --- Topology ---
    MISSING_INPUT_NODE = "MISSING_INPUT_NODE"
    MULTIPLE_INPUT_NODES = "MULTIPLE_INPUT_NODES"
    MISSING_OUTPUT_NODE = "MISSING_OUTPUT_NODE"
    INVALID_INPUT_NODE_EDGE = "INVALID_INPUT_NODE_EDGE"
    INVALID_OUTPUT_NODE_EDGE = "INVALID_OUTPUT_NODE_EDGE"
    UNSUPPORTED_CYCLE = "UNSUPPORTED_CYCLE"
    UNREACHABLE_NODE = "UNREACHABLE_NODE"
    DEAD_END_BRANCH = "DEAD_END_BRANCH"
    INVALID_PARALLEL = "INVALID_PARALLEL"
    INVALID_MERGE = "INVALID_MERGE"
    INVALID_PARALLEL_MERGE_STRUCTURE = "INVALID_PARALLEL_MERGE_STRUCTURE"

    # --- Registry references ---
    MISSING_AGENT_REFERENCE = "MISSING_AGENT_REFERENCE"
    AGENT_NOT_FOUND = "AGENT_NOT_FOUND"
    AGENT_DISABLED = "AGENT_DISABLED"
    AGENT_UNHEALTHY = "AGENT_UNHEALTHY"
    MISSING_SERVICE_REFERENCE = "MISSING_SERVICE_REFERENCE"
    SERVICE_NOT_FOUND = "SERVICE_NOT_FOUND"
    SERVICE_DISABLED = "SERVICE_DISABLED"
    SERVICE_UNHEALTHY = "SERVICE_UNHEALTHY"
    MISSING_SERVICE_ACTION_REFERENCE = "MISSING_SERVICE_ACTION_REFERENCE"
    SERVICE_ACTION_NOT_FOUND = "SERVICE_ACTION_NOT_FOUND"
    SERVICE_ACTION_DISABLED = "SERVICE_ACTION_DISABLED"
    SERVICE_ACTION_MISMATCH = "SERVICE_ACTION_MISMATCH"

    # --- Node configuration ---
    MISSING_REQUIRED_CONFIG = "MISSING_REQUIRED_CONFIG"
    INVALID_CONDITION = "INVALID_CONDITION"
    INVALID_CONDITION_OPERATOR = "INVALID_CONDITION_OPERATOR"
    INVALID_CONDITION_BRANCH = "INVALID_CONDITION_BRANCH"
    INVALID_WAIT_CONFIG = "INVALID_WAIT_CONFIG"
    UNSUPPORTED_WAIT_MODE = "UNSUPPORTED_WAIT_MODE"
    INVALID_HUMAN_CONFIG = "INVALID_HUMAN_CONFIG"
    INVALID_DATA_INPUT = "INVALID_DATA_INPUT"
    INVALID_DATA_OUTPUT = "INVALID_DATA_OUTPUT"
    INVALID_TRANSFORM_CONFIG = "INVALID_TRANSFORM_CONFIG"

    # --- Context references ---
    INVALID_CONTEXT_REFERENCE = "INVALID_CONTEXT_REFERENCE"
    UNKNOWN_CONTEXT_NODE = "UNKNOWN_CONTEXT_NODE"
    UNKNOWN_VARIABLE = "UNKNOWN_VARIABLE"
    INVALID_OUTPUT_REFERENCE = "INVALID_OUTPUT_REFERENCE"
    UNKNOWN_WORKFLOW_INPUT = "UNKNOWN_WORKFLOW_INPUT"
    INVALID_DATA_DEPENDENCY = "INVALID_DATA_DEPENDENCY"
    INVALID_PARALLEL_DATA_DEPENDENCY = "INVALID_PARALLEL_DATA_DEPENDENCY"

    # --- Input mapping / schema ---
    INVALID_INPUT_MAPPING = "INVALID_INPUT_MAPPING"
    UNKNOWN_INPUT_FIELD = "UNKNOWN_INPUT_FIELD"
    MISSING_REQUIRED_INPUT = "MISSING_REQUIRED_INPUT"
    SCHEMA_TYPE_MISMATCH = "SCHEMA_TYPE_MISMATCH"
